### ISSUE TITLE
ダウンロードできなくなった

### ISSUE THREAD

**Issue by MI2-2** [fa0311/jump-downloader-for-windows#14]
2024年45号からダウンロード時にエラーが表示されるようになりました。

**Comment by guohao414** [comment]
> 2024年45号からダウンロード時にエラーが表示されるようになりました。

なんか最新からWebサイトのJSONファイルがうまく取得できなくなっているようですね。。。
HTMLからJSONファイルを取り出し、それを元にダウンロードするようにツールを改造し、
何とかダウンロードできたが、根本的な解決策ではないので、どうしようかなと思っていました。

**Comment by fa0311** [comment]
これは既知の問題で気が向いたら治します

ref: https://github.com/eggplants/getjump/issues/264

**Comment by fa0311** [comment]
`v1.2.2` で直しました

**Comment by MI2-2** [comment]
ご対応いただき誠にありがとうございました。
無事ダウンロードができるようになりました。
